### ISSUE TITLE
async/await

### ISSUE THREAD

**Issue by duracellko** [net-ba/meetup#1]
This session is focused on coding asynchronous applications in C# using async/await keywords. It especially explains Task Parallel Library that works behind the scene. Approach is the same as my favorite author Charles Petzold used in his book about WPF. First half of the book about WPF is strictly no XAML, so that reader understands what WPF is really about. And most part of this presentation is strictly without async and await keywords.

## Agenda

- Task Parallel Library
  - What is it?
  - Parallel computing
  - Continuation
  - Exception handling
  - Cancellation
  - Child tasks
  - Scheduling
- Data Structures for Parallel Programming
- Parallel LINQ
- Thread Synchronization Context
- async/await and GetAwaiter

**Comment by jojonv** [comment]
I've been thinking about doing something similar to this. Explain the need and asynchronous programming in .NET. (async await keywords). What goes behind the scenes (state machines, etc).

**Comment by duracellko** [comment]
Thank you for your attendance.

Presentation: [https://1drv.ms/p/s!Ancl5Qq3ImPBgzwiMl03jwQ_1-uu](https://1drv.ms/p/s!Ancl5Qq3ImPBgzwiMl03jwQ_1-uu)

Exercises: [https://github.com/net-ba/tpl](https://github.com/net-ba/tpl)
