### ISSUE TITLE
App Speedup using SIMD Instructions

### ISSUE THREAD

**Issue by michalbb1** [net-ba/meetup#19]
SIMD processor instructions (Single Instruction Multiple Data) are processor instructions, that work with more data (vector of values) at once, so they perform (mainly) arithmetic operations faster.

A compiler should compile the code into SIMD processor instructions, however compiler is not omnipotent and our applications might not utilize available processing power.

There is a way how to ensure that however and I can show some real life examples, where and how can this approach be applicable.

**Comment by jakubsturc** [comment]
Thank you. Good session. Great discussion.
