### ISSUE TITLE
Using Protocol Buffers in .NET

### ISSUE THREAD

**Issue by jakubsturc** [net-ba/meetup#20]
For description see comment by @Ladislav-Macejak below

**Comment by Ladislav-Macejak** [comment]
Presentation will introduced protocol buffers and the advantages that they can bring to an application. Protocol buffers are very well suited for micro service based architectures and are also used in gRPC framework

We will cover:
	• Performance comparison between protocol buffers and competing protocols XML & JSON
	• Syntax that is used to define messages to be used with protocol buffers
        • Features and practices that allow messages to evolve without breaking older applications
