### ISSUE TITLE
Vertical Slice Architecture

### ISSUE THREAD

**Issue by dorny** [net-ba/meetup#23]
Vertical (feature) slices are an alternative to better known layered architecture.
This architecture style is a great fit for web APIs. I would like to talk about:
* Definition of "Vertical slice" concept
* Pros & Cons of slices vs layered (onion) architecture
* Example App - CQRS API using ASP.NET Core and MediatR
* My experience with applying vertical slices on actual project

**Comment by jakubsturc** [comment]
You can check video on the talk at youtube. https://youtu.be/XoSG3n45ivE
