### ISSUE TITLE
C# 7+ - safe high performance code

### ISSUE THREAD

**Issue by mareklinka** [net-ba/meetup#29]
C# 7 introduced `Span<T>` and `Memory<T>` structures that allow for increased performance. However, there are a lot of other concepts that extend our ability to write safe yet fast code:

* ref structs
* in parameters
* ref locals and returns
* stackalloc
* ref ternaries
* and more

It's also one thing to know these exist and a different thing to know how they work. I'd like to dive deeper into these constructs and peek behind the curtain of writing high-throughput, low-allocation code.

**Comment by jakubsturc** [comment]
You can see talk at https://youtu.be/LgPSOmr6e-0
Slides and code are at https://github.com/mareklinka/dotnetba-internals
