### ISSUE TITLE
NuGet in C# projects

### ISSUE THREAD

**Issue by duracellko** [net-ba/meetup#3]
- Consume packages
- Generate packages
- Multi-platform packages
- old vs new csproj format & NuGet

**Comment by Michal-Svoboda** [comment]
In spite of there is quite large [NuGet documentation](https://docs.microsoft.com/en-us/nuget/) (including shorten [Quick Start](https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package)), this does not cover straightforward manual how to deal with NuGets during the whole Continuous Integration process. This meetup will try to fill this gap.

- NuGet usage prerequisities
- Consume NuGet packages
- Generate NuGet packages
   - Generate NuGet package for several platforms
        - Multi-targets in the new "Microsoft.NET.Sdk" csproj file format
        - Multi-targets in the "classic" csproj file format
- Publish NuGet packages
   - Shared folder for hosting NuGet packages
- Advantages / Disadvantages of the new "Microsoft.NET.Sdk" csproj file

**Comment by Michal-Svoboda** [comment]
The materials to the presented topic "NuGet in C# projects" can be found here: https://github.com/net-ba/NuGetInCSharp
