### ISSUE TITLE
System.IO.Pipes - high performance async IO the easy way

### ISSUE THREAD

**Issue by mareklinka** [net-ba/meetup#30]
The `System.IO.Pipes` namespace is a new way of doing high-performance async IO (mostly network) in .NET. It was created to speed up Kestrel (the ASP.NET Core standalone server) and greatly simplifies the process of writing correct networking code.

It might be interested to see a demo and maybe foster a discussion about where else this tech can be useful to application developers.

**Comment by jakubsturc** [comment]
Done by @menyet.

https://youtu.be/It0Q2h_zoKY

**Comment by juzwos** [comment]
Hi
It is possible to get the code from the presentation?
