### ISSUE TITLE
Introduction to quantum computing and Microsoft Q# language

### ISSUE THREAD

**Issue by michalbb1** [net-ba/meetup#36]
Quantum computing has been something that I considered sci-fi or a thing of the future. But it's becoming more real every day and today you can already try out quantum computing by yourself.

In this session, I would like to present some basics of quantum computing, a bit of theory behind it and a real world example of a quantum algorithm.

Finally we will have a look at Q# language, that is being developed by Microsoft for writing quantum algorithms and how to set it up in Visual Studio.

**Comment by jakubsturc** [comment]
https://youtu.be/-LmTHOC_7FA
