### ISSUE TITLE
DAPR for ASP.NET Core developers

### ISSUE THREAD

**Issue by mareklinka** [net-ba/meetup#39]
So, Microsoft very recently released this thing called [DAPR](https://dapr.io/) (Distributed APplication Runtime). This framework seeks to drastically simplify the creation of distriubuted/micro-service applications by providing a set of configurable building blocks for the most common scenarios (e.g. persistent storage, pub/sub, monitoring etc.).

I think this is an amazing idea and even though it's just an alpha at this point, it would be cool to see what it's capable of.

**Comment by mareklinka** [comment]
Demo repository for the meetup talk: https://github.com/mareklinka/dotnetba-dapr

**Comment by jakubsturc** [comment]
Video from the meetup (in Slovak). 
https://youtu.be/s-o87-mAm6k
