### ISSUE TITLE
Creation of Asp.Net Core web service with NSwag and API First approach

### ISSUE THREAD

**Issue by milung** [net-ba/meetup#43]
We use APIFirst approach when distributing work to multiple teams/technologies, specifically designing RestFull API-s for web service and in parallel for the Web Client.  In this meetup I will present how to do API-First approach effectively with Swagger and NSwag, using their code generation features for ASP.NET Core and Angular. 

The topic assumes basic knowledge of ASP.NET Core >2.2  and of Restfull principles.

**Comment by jakubsturc** [comment]
https://youtu.be/l7jNIQdghhw
