### ISSUE TITLE
.NET Standard

### ISSUE THREAD

**Issue by duracellko** [net-ba/meetup#5]
One library to rule them all
- What is difference between Portable Class Library and .NET Standard
- How does it work?
- What is difference between Common Language Infrastructure and .NET Standard
- New csproj format
- How can you take advantage of it in existing projects, or when not targeting multiple platforms

**Comment by jakubsturc** [comment]
@duracellko: Should I keep it open or should I close this one? Partially it was covers on Meetup #3 in May. What do you think?

**Comment by duracellko** [comment]
I think it can be closed. We can get back to it, if anyone requests similar topic.
